name: Build and Deploy Code

on: [push, pull_request]
jobs:
  build:
    runs-on: self-hosted
    environment:
      name: testing
    env:
      DATABASE_HOSTNAME: ${{ secrets.DATABASE_HOSTNAME }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Verify Python Version
        run: python3 --version  # Ensure Python 3.10 is used

      - name: Upgrade Pip
        run: python3 -m pip install --upgrade pip

      - name: Install Dependencies
        run: python3 -m pip install -r requirements.txt

      # - name: Run Tests
      #   run: |
      #     python3 -m pip install pytest
      #     python3 -m pytest

  deploy:
    runs-on: self-hosted
    needs: [build]
    environment:
      name: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Ubuntu Server
        run: |
          cd /app/src
          git pull origin main
          source /home/${{ secrets.PROD_USERNAME }}/venv/bin/activate
          pip install -r requirements.txt
          echo ${{ secrets.PROD_PASSWORD }} | sudo -S systemctl restart api
